//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace UploaderLibrary.ru.e3w.testphpservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="hellotestingBinding", Namespace="http://testphpservice.e3w.ru/?wsdl")]
    public partial class hellotesting : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PushValOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetValOperationCompleted;
        
        private System.Threading.SendOrPostCallback PushFileInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PullFileInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetRequiredPartOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRequiredPartOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearValOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public hellotesting() {
            this.Url = global::UploaderLibrary.Properties.Settings.Default.UploaderLibrary_ru_e3w_testphpservice_hellotesting;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PushValCompletedEventHandler PushValCompleted;
        
        /// <remarks/>
        public event GetValCompletedEventHandler GetValCompleted;
        
        /// <remarks/>
        public event PushFileInfoCompletedEventHandler PushFileInfoCompleted;
        
        /// <remarks/>
        public event PullFileInfoCompletedEventHandler PullFileInfoCompleted;
        
        /// <remarks/>
        public event SetRequiredPartCompletedEventHandler SetRequiredPartCompleted;
        
        /// <remarks/>
        public event GetRequiredPartCompletedEventHandler GetRequiredPartCompleted;
        
        /// <remarks/>
        public event ClearValCompletedEventHandler ClearValCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testphpservice.e3w.ru/index.php/PushVal", RequestNamespace="http://testphpservice.e3w.ru/?wsdl", ResponseNamespace="http://testphpservice.e3w.ru/?wsdl")]
        public void PushVal(PartialData inVal) {
            this.Invoke("PushVal", new object[] {
                        inVal});
        }
        
        /// <remarks/>
        public void PushValAsync(PartialData inVal) {
            this.PushValAsync(inVal, null);
        }
        
        /// <remarks/>
        public void PushValAsync(PartialData inVal, object userState) {
            if ((this.PushValOperationCompleted == null)) {
                this.PushValOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushValOperationCompleted);
            }
            this.InvokeAsync("PushVal", new object[] {
                        inVal}, this.PushValOperationCompleted, userState);
        }
        
        private void OnPushValOperationCompleted(object arg) {
            if ((this.PushValCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushValCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testphpservice.e3w.ru/index.php/GetVal", RequestNamespace="http://testphpservice.e3w.ru/?wsdl", ResponseNamespace="http://testphpservice.e3w.ru/?wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public PartialData GetVal() {
            object[] results = this.Invoke("GetVal", new object[0]);
            return ((PartialData)(results[0]));
        }
        
        /// <remarks/>
        public void GetValAsync() {
            this.GetValAsync(null);
        }
        
        /// <remarks/>
        public void GetValAsync(object userState) {
            if ((this.GetValOperationCompleted == null)) {
                this.GetValOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetValOperationCompleted);
            }
            this.InvokeAsync("GetVal", new object[0], this.GetValOperationCompleted, userState);
        }
        
        private void OnGetValOperationCompleted(object arg) {
            if ((this.GetValCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetValCompleted(this, new GetValCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testphpservice.e3w.ru/index.php/PushFileInfo", RequestNamespace="http://testphpservice.e3w.ru/?wsdl", ResponseNamespace="http://testphpservice.e3w.ru/?wsdl")]
        public void PushFileInfo(FileInfoData inVal) {
            this.Invoke("PushFileInfo", new object[] {
                        inVal});
        }
        
        /// <remarks/>
        public void PushFileInfoAsync(FileInfoData inVal) {
            this.PushFileInfoAsync(inVal, null);
        }
        
        /// <remarks/>
        public void PushFileInfoAsync(FileInfoData inVal, object userState) {
            if ((this.PushFileInfoOperationCompleted == null)) {
                this.PushFileInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushFileInfoOperationCompleted);
            }
            this.InvokeAsync("PushFileInfo", new object[] {
                        inVal}, this.PushFileInfoOperationCompleted, userState);
        }
        
        private void OnPushFileInfoOperationCompleted(object arg) {
            if ((this.PushFileInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushFileInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testphpservice.e3w.ru/index.php/PullFileInfo", RequestNamespace="http://testphpservice.e3w.ru/?wsdl", ResponseNamespace="http://testphpservice.e3w.ru/?wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public FileInfoData PullFileInfo() {
            object[] results = this.Invoke("PullFileInfo", new object[0]);
            return ((FileInfoData)(results[0]));
        }
        
        /// <remarks/>
        public void PullFileInfoAsync() {
            this.PullFileInfoAsync(null);
        }
        
        /// <remarks/>
        public void PullFileInfoAsync(object userState) {
            if ((this.PullFileInfoOperationCompleted == null)) {
                this.PullFileInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPullFileInfoOperationCompleted);
            }
            this.InvokeAsync("PullFileInfo", new object[0], this.PullFileInfoOperationCompleted, userState);
        }
        
        private void OnPullFileInfoOperationCompleted(object arg) {
            if ((this.PullFileInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PullFileInfoCompleted(this, new PullFileInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testphpservice.e3w.ru/index.php/SetRequiredPart", RequestNamespace="http://testphpservice.e3w.ru/?wsdl", ResponseNamespace="http://testphpservice.e3w.ru/?wsdl")]
        public void SetRequiredPart(int inval) {
            this.Invoke("SetRequiredPart", new object[] {
                        inval});
        }
        
        /// <remarks/>
        public void SetRequiredPartAsync(int inval) {
            this.SetRequiredPartAsync(inval, null);
        }
        
        /// <remarks/>
        public void SetRequiredPartAsync(int inval, object userState) {
            if ((this.SetRequiredPartOperationCompleted == null)) {
                this.SetRequiredPartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetRequiredPartOperationCompleted);
            }
            this.InvokeAsync("SetRequiredPart", new object[] {
                        inval}, this.SetRequiredPartOperationCompleted, userState);
        }
        
        private void OnSetRequiredPartOperationCompleted(object arg) {
            if ((this.SetRequiredPartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetRequiredPartCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testphpservice.e3w.ru/index.php/GetRequiredPart", RequestNamespace="http://testphpservice.e3w.ru/?wsdl", ResponseNamespace="http://testphpservice.e3w.ru/?wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("outval")]
        public int GetRequiredPart() {
            object[] results = this.Invoke("GetRequiredPart", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetRequiredPartAsync() {
            this.GetRequiredPartAsync(null);
        }
        
        /// <remarks/>
        public void GetRequiredPartAsync(object userState) {
            if ((this.GetRequiredPartOperationCompleted == null)) {
                this.GetRequiredPartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRequiredPartOperationCompleted);
            }
            this.InvokeAsync("GetRequiredPart", new object[0], this.GetRequiredPartOperationCompleted, userState);
        }
        
        private void OnGetRequiredPartOperationCompleted(object arg) {
            if ((this.GetRequiredPartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRequiredPartCompleted(this, new GetRequiredPartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testphpservice.e3w.ru/index.php/ClearVal", RequestNamespace="", ResponseNamespace="")]
        public void ClearVal() {
            this.Invoke("ClearVal", new object[0]);
        }
        
        /// <remarks/>
        public void ClearValAsync() {
            this.ClearValAsync(null);
        }
        
        /// <remarks/>
        public void ClearValAsync(object userState) {
            if ((this.ClearValOperationCompleted == null)) {
                this.ClearValOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearValOperationCompleted);
            }
            this.InvokeAsync("ClearVal", new object[0], this.ClearValOperationCompleted, userState);
        }
        
        private void OnClearValOperationCompleted(object arg) {
            if ((this.ClearValCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearValCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://testphpservice.e3w.ru/?wsdl")]
    public partial class PartialData {
        
        private int idField;
        
        private string dataField;
        
        private bool isCompletedField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCompleted {
            get {
                return this.isCompletedField;
            }
            set {
                this.isCompletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://testphpservice.e3w.ru/?wsdl")]
    public partial class FileInfoData {
        
        private string fileNameField;
        
        private int chunkSizeField;
        
        private int chunkCountField;
        
        private int lastChunkSizeField;
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public int ChunkSize {
            get {
                return this.chunkSizeField;
            }
            set {
                this.chunkSizeField = value;
            }
        }
        
        /// <remarks/>
        public int ChunkCount {
            get {
                return this.chunkCountField;
            }
            set {
                this.chunkCountField = value;
            }
        }
        
        /// <remarks/>
        public int LastChunkSize {
            get {
                return this.lastChunkSizeField;
            }
            set {
                this.lastChunkSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PushValCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetValCompletedEventHandler(object sender, GetValCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetValCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetValCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PartialData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PartialData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PushFileInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PullFileInfoCompletedEventHandler(object sender, PullFileInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PullFileInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PullFileInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileInfoData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileInfoData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetRequiredPartCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetRequiredPartCompletedEventHandler(object sender, GetRequiredPartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRequiredPartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRequiredPartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ClearValCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591